"""empty message

Revision ID: 24ed5c813b8f
Revises: 6c81e2343745
Create Date: 2020-08-02 21:39:42.079365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ed5c813b8f'
down_revision = '6c81e2343745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_lists', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_lists', 'completed')
    # ### end Alembic commands ###
